In [1]:
import os

In [2]:
import pandas as pd
import networkx as nx

In [3]:
from iaca import data, etl, sketch, transform
from iaca.extract import extract_python, extract_yaml
from iaca import system_tests

In [4]:
# DEBUG
import importlib

importlib.reload(data)
importlib.reload(extract_yaml)
importlib.reload(extract_python)
importlib.reload(etl)
importlib.reload(transform)
importlib.reload(system_tests)
importlib.reload(sketch)

In [5]:
architect = sketch.Architect(root_dir="..")
registry = architect.perform_registry_etl()
tests, test_results = architect.validate_registry(
    min_priority=0.5,
    allowed_infrastructure=["iaca_infrastructure"],
)

/Users/zhafen/repos/iaca/.venv/lib/python3.13/site-packages/pandera/backends/pandas/container.py:569: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  check_obj[col_name] = check_obj[col_name].fillna(

entity: iaca/system_tests.test_designed
requirement: fully_designed
priority: 0.9
description:
    Each [requirement] entity has at least one [satisfies] entity or one [child]
    entity.
test_passed: False
failed_components:

,entity,requirement.comp_key,requirement.priority,requirement.value,link.link_type,link.source,link.target,status.comp_key,status.value,test.comp_key,test.value
1,can_budget_for_preference_and_fit,1,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,can_build_requirements_map,1,0.9,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,can_calculate_the_most_efficient_paths,1,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,can_document_workflows,1,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,compatible_with_a_config,1,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,compliments_existing_agile_approaches,1,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,directly_calls_agents,1,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,enables_reconciliation_via_postprocessing,1,0.7,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,facilitates_a_source_of_truth,0,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,has_an_mcp_server,1,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,supports_easy_lookup,1,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,syntax_is_brief,0,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,syntax_is_flexible,1,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------------------------------------

entity: iaca/system_tests.test_defined
requirement: fully_defined
priority: 0.8
description:
    All [compdef] entities are defined and valid.
test_passed: False
failed_components:

,comp_key,multiplicity,normalize,unparsed_fields,is_defined,fields,is_valid,errors
entity,,,,,,,,
specifications,0,0..*,True,{},False,"{'entity': <Schema Field(name=entity, type=Dat...",False,Component definition does not exist.

--------------------------------------------------------------------------------

entity: iaca/system_tests.test_implemented
requirement: fully_implemented
priority: 0.7
description:
    Meets the same criteria as "fully_designed" and all [satisfies] entities
    either have a test that passes when executed or have a status of "in
    production".
test_passed: False
failed_components:

,entity,requirement.comp_key,requirement.priority,requirement.value,link.link_type,link.source,link.target,status.comp_key,status.value,test.comp_key,test.value
0,accepts_nested_entities_as_children,1,0.9,iaca_infrastructure,satisfies,iaca/extract/extract_yaml.YAMLExtractor.parse_...,accepts_nested_entities_as_children,NaN,NaN,NaN,NaN
1,can_budget_for_preference_and_fit,1,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,can_build_requirements_map,1,0.9,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,can_calculate_the_most_efficient_paths,1,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,can_document_workflows,1,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,can_perform_registry_etl,1,0.5,NaN,satisfies,perform_registry_etl,can_perform_registry_etl,NaN,NaN,NaN,NaN
12,compatible_with_a_config,1,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,compliments_existing_agile_approaches,1,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,directly_calls_agents,1,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,enables_reconciliation_via_postprocessing,1,0.7,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,facilitates_a_source_of_truth,0,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,has_an_mcp_server,1,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,stores_manifest_data_in_a_useful_format,1,0.5,iaca_infrastructure,satisfies,manifest_in_docstore_db,stores_manifest_data_in_a_useful_format,NaN,NaN,NaN,NaN
45,stores_manifest_data_in_a_useful_format,1,0.5,iaca_infrastructure,satisfies,manifest_in_relational_db,stores_manifest_data_in_a_useful_format,NaN,NaN,NaN,NaN
46,supports_easy_lookup,1,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,syntax_is_brief,0,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,syntax_is_flexible,1,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------------------------------------

entity: iaca/system_tests.test_no_forbidden_components
requirement: no_forbidden_components
priority: 0.5
description:
    No [error], [todo], or other "forbidden" components.
test_passed: False
failed_components:

,entity,comp_key,value
0,FunctionDef,4,Allow components to be defined in the doc stri...
1,Module,2,Reconcile the paths s.t. we can easily and acc...
2,child,4,Currently child links are used for both specif...
3,child_component,1,Consider if we can roll this up into a more ge...
4,component,5,Can we condense the formatting for multiple co...
5,component,6,Can we allow entities to be defined inside oth...
6,documentation,3,"The value of documentation is a path, so it sh..."
7,foreign_keys,3,The logic to parse this is not yet implemented.
8,iaca/data.Registry.__getitem__,0,We could return an empty DataFrame with a defi...
9,iaca/data.Registry.__init__,0,Something about initializing with a parameter_...
10,iaca/etl.TransformSystem.build_graph_from_links,0,"Probably delete this, because it makes more se..."
11,iaca/etl.TransformSystem.normalize_components,0,Don't hardcode the skip_normalization list her...
12,iaca/sketch.Architect.__init__,0,There should be no parameters that aren't in t...
13,iaca/sketch.Architect.perform_registry_etl,2,"Point to the unit test for this, instead of ch..."
14,iaca/sketch.Architect.validate_registry,3,"Point to the unit test for this, instead of ch..."
15,iaca/sketch.Architect.validate_registry,4,Currently we're only set up to run tests that ...
16,iaca/sketch.Architect.validate_registry,5,Tests that are imported as Python code are cur...
17,iaca/sketch.Architect.validate_registry,6,Is this function suffering from trying to be t...
18,iaca/sketch.Architect.validate_registry,7,"The errors are often mangled. For example, a K..."
19,iaca/system_tests.test_implemented,2,Add code that identifies parent nodes with uns...
20,iaca/system_tests.test_no_forbidden_components,2,Add priority cutoff.
21,iaca/transform/preprocess.ComponentNormalizer....,0,"The way this is set up currently, no component..."
22,iaca/transform/preprocess.ComponentValidator,0,Add validation that warns users when they try ...
23,link_type,3,Get rid of reverse relations and just use the ...
24,parent,4,"Reverse this with child, since that produces a..."
25,requirement,4,I think it's pretty confusing to have requirem...
26,validate_compinsts,3,Update to use pydantic.
27,fields,2,Parsing fails if the user doesn't specify the ...

--------------------------------------------------------------------------------

In [6]:
min_priority = 0.5
reqs = registry.view(["requirement", "description", "status"])
reqs = reqs.loc[reqs["requirement.priority"] >= min_priority]
reqs

,requirement.comp_key,requirement.priority,requirement.value,description.comp_key,description.value,status.comp_key,status.value
entity,,,,,,,
accepts_nested_entities_as_children,1,0.9,iaca_infrastructure,0,"The files are very hard to follow right now, i...",NaN,NaN
can_budget_for_preference_and_fit,1,0.5,iaca_infrastructure,0,The most efficient path isn't necessarily real...,NaN,NaN
can_build_delivery_plan,1,0.5,iaca_infrastructure,0,"Given a set of prioritized requirements, can b...",NaN,NaN
can_build_requirements_map,1,0.9,iaca_infrastructure,0,A requirements map is a visual representation ...,NaN,NaN
can_calculate_the_most_efficient_paths,1,0.5,iaca_infrastructure,0,"Given a set of prioritized requirements, can s...",NaN,NaN
can_document_workflows,1,0.5,NaN,0,iaca must provide functionality to document sy...,NaN,NaN
can_execute_tests,1,0.5,NaN,0,iaca must run all validation tests to verify s...,NaN,NaN
can_incorporate_poorly_formed_components,1,0.5,iaca_infrastructure,0,While gathering information it is common to co...,NaN,NaN
can_perform_registry_etl,1,0.5,NaN,0,iaca must perform extract-transform-load opera...,NaN,NaN
compatible_with_a_config,1,0.5,iaca_infrastructure,0,Parameters for iaca should be set in the provi...,NaN,NaN
compliments_existing_agile_approaches,1,0.5,iaca_infrastructure,0,There's no way iaca can compete with the level...,NaN,NaN
directly_calls_agents,1,0.5,iaca_infrastructure,0,Probably want to use langchain for this.,NaN,NaN
documentation_coverage_is_high,5,0.5,quality_infrastructure,0,A requirement ensuring that most system compon...,NaN,NaN
documentation_quality_is_high,1,0.5,quality_infrastructure,0,Who is the speaker? What are the technical ter...,NaN,NaN
documentation_uses_consistent_perspective,1,0.5,quality_infrastructure,0,A requirement ensuring documentation maintains...,NaN,NaN
documentation_uses_consistent_terminology,1,0.5,quality_infrastructure,0,A requirement ensuring that technical terms ar...,NaN,NaN
documents_system_architecture,1,0.5,iaca_infrastructure,0,At any given time the code that defines the sy...,NaN,NaN
draws_on_widely_used_system_design_terminology,1,0.5,quality_infrastructure,0,E.g. the url(s) attached.,NaN,NaN
enables_iterative_system_decomposition,1,0.5,iaca_infrastructure,0,The requirements and components of complicated...,NaN,NaN
enables_reconciliation_via_postprocessing,1,0.7,iaca_infrastructure,0,"After the user defines their yaml, having the ...",NaN,NaN
facilitates_a_source_of_truth,0,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN
facilitates_system_design,0,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN
fully_defined,1,0.8,NaN,0,All [compdef] entities are defined and valid.,NaN,NaN
fully_designed,1,0.9,NaN,0,Each [requirement] entity has at least one [sa...,NaN,NaN
fully_implemented,1,0.7,NaN,0,"Meets the same criteria as ""fully_designed"" an...",NaN,NaN
has_a_good_name,1,0.5,quality_infrastructure,0,A good name goes a long way.\n,NaN,NaN
has_an_mcp_server,1,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN
has_good_documentation,1,0.5,quality_infrastructure,0,A requirement ensuring that the system provide...,NaN,NaN
has_good_syntax,1,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN
implements_systems,0,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN
is_a_useful_tool,1,0.5,iaca_infrastructure,0,"Fundamentally, iaca must serve a purpose.\n",NaN,NaN
is_marketable,1,0.5,iaca_infrastructure,0,It doesn't matter how good the system is if yo...,NaN,NaN
minimizes_structure_repetition,1,0.5,iaca_infrastructure,0,iaca should not require the user to go through...,NaN,NaN
no_forbidden_components,1,0.5,NaN,0,"No [error], [todo], or other ""forbidden"" compo...",NaN,NaN
reconciles_user_components,1,0.9,iaca_infrastructure,0,Users should be able to easily reconcile (de-d...,NaN,NaN
records_system_architecture,0,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN
stores_manifest_data_in_a_useful_format,1,0.5,iaca_infrastructure,0,The format we store the data in facilitates di...,NaN,NaN
supports_easy_lookup,1,0.5,NaN,0,When designing a system in yaml it's essential...,NaN,NaN
syntax_is_brief,0,0.5,iaca_infrastructure,NaN,NaN,NaN,NaN
syntax_is_flexible,1,0.5,iaca_infrastructure,0,Syntax can be used to describe nearly arbitrar...,NaN,NaN
terminology_is_externally_consistent,1,0.5,quality_infrastructure,0,Are the terms used in iaca consistent with com...,NaN,NaN
terminology_is_internally_consistent,1,0.5,quality_infrastructure,0,"For terms defined inside iaca, are they used c...",NaN,NaN
uses_consistent_ecs_terminology,1,0.5,quality_infrastructure,0,"Unfortunately, ""system"" and ""component"" are us...",NaN,NaN
validates_system_architecture,1,0.5,iaca_infrastructure,0,iaca must provide a series of automated tests ...,NaN,NaN
works_with_llms_to_implement_systems,1,0.5,iaca_infrastructure,0,"Reflecting on this, this is low priority becau...",NaN,NaN

In [7]:
reqs["description.sanitized"] = reqs["description.value"].str.replace("\n", " ").str.replace('"', "'")

In [8]:
def_body = ""
for entity, req in reqs.iterrows():
    def_body += f"requirement {entity} {{"
    if not pd.isna(req["description.sanitized"]):
        def_body += f'\n    text: "{req["description.sanitized"]}"'
    def_body += "\n}\n\n"
print(def_body)

requirement accepts_nested_entities_as_children {
    text: "The files are very hard to follow right now, in regards to parents and children. Allowing nesting as code works should be both straightforward and greatly improve readability. "
}

requirement can_budget_for_preference_and_fit {
    text: "The most efficient path isn't necessarily realistic: people have preferences and are better fits for some tasks than others. "
}

requirement can_build_delivery_plan {
    text: "Given a set of prioritized requirements, can build a delivery plan. "
}

requirement can_build_requirements_map {
    text: "A requirements map is a visual representation of requirements and the possible routes to complete them. Before deciding on any sort of algorithm, putting the data in a format for people to understand what needs to get done and how it relates comes first. "
}

requirement can_calculate_the_most_efficient_paths {
    text: "Given a set of prioritized requirements, can suggest which to do in what order. "
}

requirement can_document_workflows {
    text: "iaca must provide functionality to document system workflows and processes."
}

requirement can_execute_tests {
    text: "iaca must run all validation tests to verify system requirements are met."
}

requirement can_incorporate_poorly_formed_components {
    text: "While gathering information it is common to come across a piece of information that is clearly important, but poorly defined. We need to record such information so it can be defined and incorporated when more is known. "
}

requirement can_perform_registry_etl {
    text: "iaca must perform extract-transform-load operations on manifests to create registries."
}

requirement compatible_with_a_config {
    text: "Parameters for iaca should be set in the provided manifest."
}

requirement compliments_existing_agile_approaches {
    text: "There's no way iaca can compete with the level of features provided by leading Agile software. We need to compliment them. "
}

requirement directly_calls_agents {
    text: "Probably want to use langchain for this."
}

requirement documentation_coverage_is_high {
    text: "A requirement ensuring that most system components and features are documented."
}

requirement documentation_quality_is_high {
    text: "Who is the speaker? What are the technical terms used?"
}

requirement documentation_uses_consistent_perspective {
    text: "A requirement ensuring documentation maintains a consistent narrative voice throughout."
}

requirement documentation_uses_consistent_terminology {
    text: "A requirement ensuring that technical terms are used consistently across all documentation."
}

requirement documents_system_architecture {
    text: "At any given time the code that defines the system must be able to be compiled and turned into a digestable, clear, format. "
}

requirement draws_on_widely_used_system_design_terminology {
    text: "E.g. the url(s) attached."
}

requirement enables_iterative_system_decomposition {
    text: "The requirements and components of complicated systems are rarely known all at once, but are assembled over time in an iterative process. This process includes gathering functional requirements from the stakeholders, identifying technical requirements/constraints, trial and error, and more. One of the goals of iaca is to provide a constant, living source of truth that can be used for both the formalized design and also components and requirements not yet incorporated. "
}

requirement enables_reconciliation_via_postprocessing {
    text: "After the user defines their yaml, having the system postprocess to reconcile and then rewrite would be very helpful. "
}

requirement facilitates_a_source_of_truth {
}

requirement facilitates_system_design {
}

requirement fully_defined {
    text: "All [compdef] entities are defined and valid."
}

requirement fully_designed {
    text: "Each [requirement] entity has at least one [satisfies] entity or one [child] entity. "
}

requirement fully_implemented {
    text: "Meets the same criteria as 'fully_designed' and all [satisfies] entities either have a test that passes when executed or have a status of 'in production'. "
}

requirement has_a_good_name {
    text: "A good name goes a long way. "
}

requirement has_an_mcp_server {
}

requirement has_good_documentation {
    text: "A requirement ensuring that the system provides clear and comprehensive documentation."
}

requirement has_good_syntax {
}

requirement implements_systems {
}

requirement is_a_useful_tool {
    text: "Fundamentally, iaca must serve a purpose. "
}

requirement is_marketable {
    text: "It doesn't matter how good the system is if you cannot convince anyone to use it. "
}

requirement minimizes_structure_repetition {
    text: "iaca should not require the user to go through code and transcribe the structure into yaml when it's already defined. Possible solutions: 1. Automatically retrieve structure from the code. 2. Use the structure in the yaml to define code execution order "
}

requirement no_forbidden_components {
    text: "No [error], [todo], or other 'forbidden' components."
}

requirement reconciles_user_components {
    text: "Users should be able to easily reconcile (de-duplicate and match formatting) between components they define on the fly and components that already exist, either theirs or in the system. "
}

requirement records_system_architecture {
}

requirement stores_manifest_data_in_a_useful_format {
    text: "The format we store the data in facilitates different applications."
}

requirement supports_easy_lookup {
    text: "When designing a system in yaml it's essential that it's easy to find components that may fit. Auto-complete in yaml would be good. "
}

requirement syntax_is_brief {
}

requirement syntax_is_flexible {
    text: "Syntax can be used to describe nearly arbitrary data."
}

requirement terminology_is_externally_consistent {
    text: "Are the terms used in iaca consistent with community standards? For example, are the relationships for requirement diagrams sufficiently consistent? "
}

requirement terminology_is_internally_consistent {
    text: "For terms defined inside iaca, are they used consistently throughout? "
}

requirement uses_consistent_ecs_terminology {
    text: "Unfortunately, 'system' and 'component' are used in two different contexts currently--as part of system design (where components are pieces of a system) and as part of entity-component-system (where components are data). "
}

requirement validates_system_architecture {
    text: "iaca must provide a series of automated tests that ensure the system architecture meets requirements. "
}

requirement works_with_llms_to_implement_systems {
    text: "Reflecting on this, this is low priority because it's already a very competitive space. Setting up an mcp server is probably a good idea, but calling agents is probably not helpful. "
}

In [9]:
links = registry.view("link")
links = links.loc[links["source"].isin(reqs.index) & links["target"].isin(reqs.index)]

In [10]:
from textwrap import indent

In [11]:
lines = links["target"] + " - derives -> " + links["source"]

arrow_body = "\n".join(lines)

In [12]:
mermaid_str = f"""
requirementDiagram

{def_body}

{arrow_body}
"""
print(mermaid_str)

requirementDiagram

requirement accepts_nested_entities_as_children {
    text: "The files are very hard to follow right now, in regards to parents and children. Allowing nesting as code works should be both straightforward and greatly improve readability. "
}

requirement can_budget_for_preference_and_fit {
    text: "The most efficient path isn't necessarily realistic: people have preferences and are better fits for some tasks than others. "
}

requirement can_build_delivery_plan {
    text: "Given a set of prioritized requirements, can build a delivery plan. "
}

requirement can_build_requirements_map {
    text: "A requirements map is a visual representation of requirements and the possible routes to complete them. Before deciding on any sort of algorithm, putting the data in a format for people to understand what needs to get done and how it relates comes first. "
}

requirement can_calculate_the_most_efficient_paths {
    text: "Given a set of prioritized requirements, can suggest which to do in what order. "
}

requirement can_document_workflows {
    text: "iaca must provide functionality to document system workflows and processes."
}

requirement can_execute_tests {
    text: "iaca must run all validation tests to verify system requirements are met."
}

requirement can_incorporate_poorly_formed_components {
    text: "While gathering information it is common to come across a piece of information that is clearly important, but poorly defined. We need to record such information so it can be defined and incorporated when more is known. "
}

requirement can_perform_registry_etl {
    text: "iaca must perform extract-transform-load operations on manifests to create registries."
}

requirement compatible_with_a_config {
    text: "Parameters for iaca should be set in the provided manifest."
}

requirement compliments_existing_agile_approaches {
    text: "There's no way iaca can compete with the level of features provided by leading Agile software. We need to compliment them. "
}

requirement directly_calls_agents {
    text: "Probably want to use langchain for this."
}

requirement documentation_coverage_is_high {
    text: "A requirement ensuring that most system components and features are documented."
}

requirement documentation_quality_is_high {
    text: "Who is the speaker? What are the technical terms used?"
}

requirement documentation_uses_consistent_perspective {
    text: "A requirement ensuring documentation maintains a consistent narrative voice throughout."
}

requirement documentation_uses_consistent_terminology {
    text: "A requirement ensuring that technical terms are used consistently across all documentation."
}

requirement documents_system_architecture {
    text: "At any given time the code that defines the system must be able to be compiled and turned into a digestable, clear, format. "
}

requirement draws_on_widely_used_system_design_terminology {
    text: "E.g. the url(s) attached."
}

requirement enables_iterative_system_decomposition {
    text: "The requirements and components of complicated systems are rarely known all at once, but are assembled over time in an iterative process. This process includes gathering functional requirements from the stakeholders, identifying technical requirements/constraints, trial and error, and more. One of the goals of iaca is to provide a constant, living source of truth that can be used for both the formalized design and also components and requirements not yet incorporated. "
}

requirement enables_reconciliation_via_postprocessing {
    text: "After the user defines their yaml, having the system postprocess to reconcile and then rewrite would be very helpful. "
}

requirement facilitates_a_source_of_truth {
}

requirement facilitates_system_design {
}

requirement fully_defined {
    text: "All [compdef] entities are defined and valid."
}

requirement fully_designed {
    text: "Each [requirement] entity has at least one [satisfies] entity or one [child] entity. "
}

requirement fully_implemented {
    text: "Meets the same criteria as 'fully_designed' and all [satisfies] entities either have a test that passes when executed or have a status of 'in production'. "
}

requirement has_a_good_name {
    text: "A good name goes a long way. "
}

requirement has_an_mcp_server {
}

requirement has_good_documentation {
    text: "A requirement ensuring that the system provides clear and comprehensive documentation."
}

requirement has_good_syntax {
}

requirement implements_systems {
}

requirement is_a_useful_tool {
    text: "Fundamentally, iaca must serve a purpose. "
}

requirement is_marketable {
    text: "It doesn't matter how good the system is if you cannot convince anyone to use it. "
}

requirement minimizes_structure_repetition {
    text: "iaca should not require the user to go through code and transcribe the structure into yaml when it's already defined. Possible solutions: 1. Automatically retrieve structure from the code. 2. Use the structure in the yaml to define code execution order "
}

requirement no_forbidden_components {
    text: "No [error], [todo], or other 'forbidden' components."
}

requirement reconciles_user_components {
    text: "Users should be able to easily reconcile (de-duplicate and match formatting) between components they define on the fly and components that already exist, either theirs or in the system. "
}

requirement records_system_architecture {
}

requirement stores_manifest_data_in_a_useful_format {
    text: "The format we store the data in facilitates different applications."
}

requirement supports_easy_lookup {
    text: "When designing a system in yaml it's essential that it's easy to find components that may fit. Auto-complete in yaml would be good. "
}

requirement syntax_is_brief {
}

requirement syntax_is_flexible {
    text: "Syntax can be used to describe nearly arbitrary data."
}

requirement terminology_is_externally_consistent {
    text: "Are the terms used in iaca consistent with community standards? For example, are the relationships for requirement diagrams sufficiently consistent? "
}

requirement terminology_is_internally_consistent {
    text: "For terms defined inside iaca, are they used consistently throughout? "
}

requirement uses_consistent_ecs_terminology {
    text: "Unfortunately, 'system' and 'component' are used in two different contexts currently--as part of system design (where components are pieces of a system) and as part of entity-component-system (where components are data). "
}

requirement validates_system_architecture {
    text: "iaca must provide a series of automated tests that ensure the system architecture meets requirements. "
}

requirement works_with_llms_to_implement_systems {
    text: "Reflecting on this, this is low priority because it's already a very competitive space. Setting up an mcp server is probably a good idea, but calling agents is probably not helpful. "
}



can_build_delivery_plan - derives -> can_build_requirements_map
can_build_delivery_plan - derives -> can_calculate_the_most_efficient_paths
can_build_delivery_plan - derives -> can_budget_for_preference_and_fit
enables_iterative_system_decomposition - derives -> can_incorporate_poorly_formed_components
is_a_useful_tool - derives -> compatible_with_a_config
is_a_useful_tool - derives -> compliments_existing_agile_approaches
has_good_documentation - derives -> documentation_coverage_is_high
has_good_documentation - derives -> documentation_quality_is_high
documentation_quality_is_high - derives -> documentation_uses_consistent_perspective
documentation_quality_is_high - derives -> documentation_uses_consistent_terminology
documents_system_architecture - derives -> stores_manifest_data_in_a_useful_format
is_a_useful_tool - derives -> documents_system_architecture
terminology_is_externally_consistent - derives -> draws_on_widely_used_system_design_terminology
facilitates_system_design - derives -> enables_iterative_system_decomposition
enables_iterative_system_decomposition - derives -> facilitates_a_source_of_truth
is_a_useful_tool - derives -> facilitates_system_design
is_marketable - derives -> has_a_good_name
has_good_syntax - derives -> syntax_is_brief
has_good_syntax - derives -> syntax_is_flexible
records_system_architecture - derives -> has_good_syntax
implements_systems - derives -> works_with_llms_to_implement_systems
implements_systems - derives -> reconciles_user_components
is_a_useful_tool - derives -> implements_systems
is_a_useful_tool - derives -> is_marketable
reconciles_user_components - derives -> enables_reconciliation_via_postprocessing
records_system_architecture - derives -> accepts_nested_entities_as_children
is_a_useful_tool - derives -> records_system_architecture
documentation_uses_consistent_terminology - derives -> terminology_is_externally_consistent
documentation_uses_consistent_terminology - derives -> terminology_is_internally_consistent
terminology_is_internally_consistent - derives -> uses_consistent_ecs_terminology
is_a_useful_tool - derives -> validates_system_architecture
works_with_llms_to_implement_systems - derives -> has_an_mcp_server
works_with_llms_to_implement_systems - derives -> directly_calls_agents

In [13]:
with open("./sketch.mmd", "w", encoding="utf-8") as f:
    f.write(mermaid_str)

In [14]:
import base64
import io, requests
from IPython.display import Image, display
from PIL import Image as im
import matplotlib.pyplot as plt

def mm(graph):
    graphbytes = graph.encode("utf8")
    base64_bytes = base64.urlsafe_b64encode(graphbytes)
    base64_string = base64_bytes.decode("ascii")
    img = im.open(io.BytesIO(requests.get('https://mermaid.ink/img/' + base64_string).content))
    plt.imshow(img)
    plt.axis('off') # allow to hide axis
    plt.savefig("mermaid.png")

mm(mermaid_str)

UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x11b5f68e0>

In [ ]:
# Visualize the graph
nx.draw(registry.graph, with_labels=True)

In [ ]:
import ast

In [ ]:
with open("../iaca/etl.py", "r") as f:
    source = f.read()
tree = ast.parse(source)
tree

In [ ]:
list(ast.iter_child_nodes(tree))

In [ ]:
import ast

In [ ]:
node = ast.parse("""
def my_function(x) -> int:
    return x + 1

x = my_function(5)
""")

In [ ]:
nt = ast.NodeTransformer()
nt.visit(node)

In [ ]:
nt = ast.NodeVisitor()
nt.visit(node)

In [ ]:
list(ast.iter_child_nodes(node.body[1]))

In [ ]:
node.body[1].value.func.ctx

In [ ]:
node.body[0].__class__.__name__

In [ ]:
node.body[0]._fields

In [ ]:
node.body[0].body[0].value._fields

In [ ]:
visitor = ComponentVisitor()

In [ ]:
visitor.visit(tree)

In [ ]:
pd.DataFrame(visitor.components)

In [ ]:
type(tree.body[-1])

In [ ]:
dict(ast.iter_fields(child_node))

In [ ]:
components = []
for child_node in ast.iter_child_nodes(tree.body[-1]):
    comp_i = {
        "component_type": type(child_node).__name__
    }
    components.append(comp_i)

components

In [ ]:
tree.body[-1].__dir__()

In [ ]:
for item in ast.iter_fields(tree.body[-1].body[-1]):
    print(item)

In [ ]:
visitor.visit(tree.body[-1])

In [ ]:
ast.walk(visitor.visit(tree))

In [ ]:
for item in ast.walk(tree):
    print(item)

In [ ]:
visitor.visit_Constant(tree)

In [ ]:
components = {}
for field, value in ast.iter_fields(tree):
    print(field, value)
    if isinstance(value, str)

In [ ]:
for item in ast.iter_child_nodes(transform_sys_tree):
    print(item)

In [ ]:
ast.get_source_segment(source, transform_sys_tree)

In [ ]:
ast.get_docstring(transform_sys_tree)

In [ ]:
isinstance(transform_sys_tree, ast.AST)